# Generated by Django 4.2.7 on 2024-01-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='quantity',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
